inherit_mode:
  merge:
    - Exclude
    - Include

require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - 'db/migrate/*'

Layout/IndentationWidth:
  Width: 2

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false